<?php

namespace AppBundle\Repository;

/**
 * UtilisateurStagiaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurStagiaireRepository extends \Doctrine\ORM\EntityRepository
{
}
